version: '3'

services:
  broker-server:
    build:
      context: ./broker-server
      dockerfile: ./broker-server.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1